<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Class "{class}" not found for removeAttributesByObjectClass' => 'Klasa "{class}" nie została znaleziona dla metody removeAttributesByObjectClass',
  'Failt to createEntry for ldap_add. No objectClass(es) defined!' => 'Nie udało się stworzyć wpisu poprzez ldap_add. Brak klas(y) zdefiniowanych obiektów!',
  'Ldap record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Rekord Ldap "{class}" ma nieprawidłową konfigurację dla relacji "{relation}". Wspakazny Rekord musi określać rodzaj relacji, własny atrybut, powiązaną klasę rekordu LDAP oraz obcy atrybut.',
  'Parse value from attr \'{name}\' failed! (Wrong reg pattern)' => 'Przetwarzana wartość z atrybutu \'{name}\' jest nieprawidłowa! (Zły wzór wyrażenia regularnego)',
  'The entry cannot be inserted to LDAP because it is not new.' => 'Wpis nie może zostać dodany do systemu LDAP ponieważ już w nim istnieje.',
  'The entry cannot be updated within LDAP because it is new.' => 'Wpis nie może być zaktualizowany w systemi LDAP ponieważ jest to nowy wpis.',
  'Wrong result count ({count}) on findByDn' => 'Nieprawidłowa ilość ({count}) uzyskana przez findByDn',
  'findSubTree failt: parent \'{dn}\' not read!' => 'zawiodło findSubTree: rodzic \'{dn}\' nie wczytany!',
  'findSubTree failt: used class is not type or subtype of \'LdapSubTree\'!' => 'zawiodło findSubTree: użyta klasa nie należy do typu lub podtypu \'LdapSubTree\'!',
  '{class} does not have relation "{name}".' => '{class} nie posiada relacji "{name}".',
);
