<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'findAll: neither attr nor filter set in criteria!' => 'findAll: w kryterium wyszukiwania nie ma ani atrybutów ani filtrów!',
  'ldap_add failt ({errno}): {message}' => 'zawiodło ldap_add ({errno}): {message}',
  'ldap_bind failt ({errno}): {message}' => 'zawiodło ldap_bind ({errno}): {message}',
  'ldap_connect to {server} failt' => 'zawiodło ldap_connect do {server}',
  'ldap_get_entries failt ({errno}): {message}' => 'zawiodło ldap_get_entries ({errno}): {message}',
  'ldap_list failt ({errno}): {message}' => 'zawiodło ldap_list ({errno}): {message}',
  'ldap_modify failt ({errno}): {message}' => 'zawiodło ldap_modify ({errno}): {message}',
  'ldap_read failt ({errno}): {message}' => 'zawiodło ldap_read ({errno}): {message}',
  'ldap_rename failt ({errno}): {message}' => 'zawiodło ldap_rename ({errno}): {message}',
  'ldap_search failt ({errno}): {message}' => 'zawiodło ldap_search ({errno}): {message}',
);
