<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Class "{class}" not found for removeAttributesByObjectClass' => 'Klasse "{class}" nicht gefunden für Methode removeAttributesByObjectClass()',
  'Failt to createEntry for ldap_add. No objectClass(es) defined!' => 'createEntry schlug fehl. Keine objectClass(es) definiert!',
  'Ldap record "{class}" has an invalid configuration for relation "{relation}". It must specify the relation type, the related active record class and the foreign key.' => 'Ldap record "{class}" hat eine falsche Konfiguration für die Relation "{relation}". Es muss der relation type, das own attribute, die related ldap record class and das foreign attribute definiert sein.',
  'Parse value from attr \'{name}\' failed! (Wrong reg pattern)' => 'Das parsen des Inhalts vom Attribute \'{name}\' schlug fehl! (falscher reg pattern)',
  'The entry cannot be inserted to LDAP because it is not new.' => 'Diese Node cann nicht über Ldap hinzugefügt werden, da sie nicht neu ist.',
  'The entry cannot be updated within LDAP because it is new.' => 'Diese Node kann nicht über Ldap aktualisiert werden da sie neu ist.',
  'Wrong result count ({count}) on findByDn' => 'Falsche Anzahl Ergebnisse ({count}) bei findByDn',
  'findSubTree failt: parent \'{dn}\' not read!' => 'findSubTree schlug fehl: Übergeordnete DN \'{dn}\' nicht gelesen!',
  'findSubTree failt: used class is not type or subtype of \'LdapSubTree\'!' => 'findSubTree schlug fehl: Die benutzte Klasse ist nicht \'LdapSubTree\' oder davon abgeleiter!',
  '{class} does not have relation "{name}".' => '{class} besitzt nicht die Relation "{name}".',
);
