<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'findAll: neither attr nor filter set in criteria!' => 'findAll: weder attr noch filter ist in criteria gesetzt!',
  'ldap_add failt ({errno}): {message}' => 'ldap_add schlug fehl ({errno}): {message}',
  'ldap_bind failt ({errno}): {message}' => 'ldap_bind schlug fehl ({errno}): {message}',
  'ldap_connect to {server} failt' => 'ldap_connect zu {server} schlug fehl',
  'ldap_get_entries failt ({errno}): {message}' => 'ldap_get_entries schlug fehl ({errno}): {message}',
  'ldap_list failt ({errno}): {message}' => 'ldap_list schlug fehl ({errno}): {message}',
  'ldap_modify failt ({errno}): {message}' => 'ldap_modify schlug fehl ({errno}): {message}',
  'ldap_read failt ({errno}): {message}' => 'ldap_read schlug fehl ({errno}): {message}',
  'ldap_rename failt ({errno}): {message}' => 'ldap_rename schlug fehl ({errno}): {message}',
  'ldap_search failt ({errno}): {message}' => 'ldap_search schlug fehl ({errno}): {message}',
);
